"use client";

import type { ReactNode } from "react";
import {
  AIConsole,
  AiHeroUI,
  AiWorkspaceUI,
  AiHowItWorksUI,
  AiGroundedUI,
  AiConfirmUI,
  AiGroundedSourcesUI,
  AiMultiModuleUI,
  AiDrawingUI,
  AiFinancialUI,
  AiFieldUI,
  AiDraftConfirmUI,
  AiHistoryUI,
  PiHeroUI,
  PiWorkspaceUI,
  PiHowItWorksUI,
  PiConnectedUI,
  PiGroundedUI,
  PiStatusUI,
  PiConfirmUI,
  PredHeroUI,
  PredShowcaseUI,
  PredRiskUI,
  PredDetailUI,
  PredPriorityUI,
  PredHealthUI,
  PredControlUI,
  PredForecastUI,
  PredEarlyWarningUI,
  PredSignalActionUI,
  PredTrendUI,
  AutoHeroUI,
  AutoHowItWorksUI,
  AutoShowcaseUI,
  AutoApprovalUI,
  AutoActivityLogUI,
  AutoGovernanceUI,
  DiHeroUI,
  DiQaUI,
  DiSummaryUI,
  DiExtractUI,
  DiCompareUI,
  DiSearchUI,
  DiContextUI,
  DiHowItWorksUI,
  AccountingUI,
  AccountingDashboardUI,
  AccountingApUI,
  AccountingArUI,
  AccountingProjectUI,
  AccountingReportUI,
  AccountingFlowUI,
  BidManagementUI,
  BillingWorkspaceUI,
  BillingSovUI,
  BillingProgressUI,
  BillingPayAppUI,
  BillingArUI,
  BillingFlowUI,
  BudgetJobCostDashboardUI,
  PayAppDashboardUI,
  PayAppG702UI,
  PayAppG703UI,
  PayAppRetainageUI,
  PayAppHistoryUI,
  PayAppReviewUI,
  PayAppFlowUI,
  WipDashboardUI,
  WipProjectUI,
  WipTableUI,
  WipPortfolioUI,
  WipSnapshotUI,
  WipFlowUI,
  CashDashboardUI,
  CashChartUI,
  CashInflowsUI,
  CashOutflowsUI,
  CashArApUI,
  CashProjectUI,
  CashFlowUI,
  BudgetCostCodeTableUI,
  BudgetVsActualUI,
  BudgetFlowUI,
  BudgetIntelligenceUI,
  ChangeOrderUI,
  ChangeOrderRegisterUI,
  ChangeOrderCreateUI,
  ChangeOrderDetailUI,
  ChangeOrderFlowUI,
  ChangeOrderStatusUI,
  ChangeOrderContextUI,
  CollaborationUI,
  ConnectedExperienceUI,
  CrmPipelineUI,
  CrmHeroUI,
  CrmWorkflowUI,
  CrmWorkspaceUI,
  CrmCustomerUI,
  CrmOpportunityUI,
  LeadsHeroUI,
  LeadsWorkflowUI,
  LeadsWorkspaceUI,
  LeadsDetailUI,
  LeadsDarkStoryUI,
  LeadsActivityUI,
  LeadsQualifyUI,
  LeadsFollowUpUI,
  LeadsNotesUI,
  LeadsPriorityUI,
  LeadsHandoffUI,
  LeadsPipelineDashUI,
  LeadsSourcesUI,
  WbHeroUI,
  WbTemplatePreviewUI,
  WbEditorUI,
  WbSectionEditorUI,
  WbCmsImportUI,
  WbPortfolioUI,
  WbBrandingUI,
  WbSeoUI,
  WbPublishUI,
  WbDomainUI,
  WbDnsUI,
  WbSslUI,
  WbContactLeadUI,
  CpHeroUI,
  CpShowcaseUI,
  CpPortalScreenUI,
  CpOwnerPortalUI,
  CpSubPortalUI,
  CpVendorPortalUI,
  CpArchitectPortalUI,
  CpEsignUI,
  CpPermissionsUI,
  CpActivityUI,
  CpApprovalsUI,
  CpDocumentsUI,
  CpFullPortalUI,
  DocsUI,
  DocumentCenterUI,
  DocumentConsolidateUI,
  DocumentDetailUI,
  DocumentSearchUI,
  DocumentUploadUI,
  DocumentVersionsUI,
  DrawingMarkupUI,
  DrawingRegisterUI,
  DrawingViewerDetailUI,
  DrawingsWorkflowUI,
  DrawingWorkspaceUI,
  DrawingRevisionUI,
  FieldDrawingUI,
  DailyLogDashboardUI,
  DailyLogCaptureUI,
  DailyLogDetailUI,
  DailyLogHistoryUI,
  DailyLogWorkforceUI,
  DailyLogPhotosUI,
  PunchDashboardUI,
  PunchStatusUI,
  PunchAssignUI,
  PunchCloseoutUI,
  TmTicketUI,
  TmTicketDetailUI,
  TmLaborUI,
  TmMaterialsUI,
  TmEquipmentUI,
  TmFlowUI,
  TmChangeUI,
  TmAttachmentsUI,
  TmReviewUI,
  TmDashboardUI,
  SafetyOverviewUI,
  SafetyObservationUI,
  SafetyInspectionUI,
  SafetyIncidentUI,
  SafetyActionsUI,
  SafetyFlowUI,
  MobileHomeUI,
  MobileDashboardUI,
  MobileDailyLogUI,
  MobileDrawingUI,
  MobilePhotosUI,
  MobilePunchUI,
  MobileTmUI,
  MobileSafetyUI,
  MobileWorkspaceUI,
  MobileFlowUI,
  MobileCaptureUI,
  MobileChainUI,
  SubDirectoryUI,
  SubProfileUI,
  SubReadinessUI,
  SubInsuranceUI,
  SubLienUI,
  SubAlertsUI,
  SubApprovalFlowUI,
  CompOverviewUI,
  CompHealthUI,
  CompRequirementsUI,
  CompSubReadinessUI,
  CompInsuranceUI,
  CompLienUI,
  CompAlertsUI,
  CompDocsUI,
  CompApprovalFlowUI,
  WfOverviewUI,
  WfDirectoryUI,
  WfProfileUI,
  WfCrewUI,
  WfProjectAssignUI,
  WfLaborHoursUI,
  WfTimesheetUI,
  WfTimesheetApprovalUI,
  WfCertificationsUI,
  WfPayrollSummaryUI,
  WfCostFlowUI,
  TimeOverviewUI,
  TimeWeeklyUI,
  TimeEntryUI,
  TimeLaborBreakdownUI,
  TimeProjectLaborUI,
  TimeCostCodeUI,
  TimeWorkflowUI,
  TimeApprovalQueueUI,
  TimeCostConnectionUI,
  TimePayrollSummaryUI,
  TimeMobileEntryUI,
  TimeSummaryUI,
  PrOverviewUI,
  PrWorkflowUI,
  PrPeriodUI,
  PrWorkerPayUI,
  PrLaborBreakdownUI,
  PrClassificationUI,
  PrFringeUI,
  PrSummaryUI,
  PrReviewUI,
  PrProjectLaborUI,
  PrDataQualityUI,
  EstimateUI,
  EstimatingUI,
  FinanceUI,
  PhoneUI,
  PortfolioAnalytics,
  PreconWorkspaceUI,
  ProcurementUI,
  ProjectCreateUI,
  ProjectDashboardUI,
  ProjectFinancialSummaryUI,
  ProjectPhasesTeamUI,
  ProjectSwitcherUI,
  ProjectWorkspace,
  RfiUI,
  RfiRegisterUI,
  RfiCreateUI,
  RfiDetailUI,
  RfiResponseUI,
  RfiFlowUI,
  RfiStatusUI,
  RfiContextUI,
  RfiFieldUI,
  SafetyUI,
  SheetsAsBuiltUI,
  TransmittalUI,
  ScheduleDependenciesUI,
  ScheduleExportUI,
  ScheduleGanttUI,
  ScheduleLookAheadUI,
  ScheduleRiskUI,
  ScheduleUI,
  SubmittalUI,
  SubmittalRegisterUI,
  SubmittalCreateUI,
  SubmittalDetailUI,
  SubmittalReviewUI,
  SubmittalFlowUI,
  SubmittalStatusUI,
  SubmittalWorkflowUI,
  SubmittalDocsUI,
  SubmittalFieldUI,
  TakeoffUI,
  WorkforceUI,
} from "@/components/mockups/ProductMockups";
import type { PreviewKey } from "@/lib/marketing/features/register";

const PREVIEWS: Record<PreviewKey, { node: ReactNode; dark?: boolean }> = {
  project: { node: <ProjectWorkspace /> },
  finance: { node: <FinanceUI />, dark: true },
  budgetDashboard: { node: <BudgetJobCostDashboardUI />, dark: true },
  budgetCostCodes: { node: <BudgetCostCodeTableUI />, dark: true },
  budgetVsActual: { node: <BudgetVsActualUI />, dark: true },
  budgetFlow: { node: <BudgetFlowUI /> },
  budgetIntelligence: { node: <BudgetIntelligenceUI />, dark: true },
  field: { node: <PhoneUI variant="home" raised /> },
  workforce: { node: <WorkforceUI /> },
  ai: { node: <AIConsole />, dark: true },
  connected: { node: <ConnectedExperienceUI /> },
  estimate: { node: <EstimateUI /> },
  estimating: { node: <EstimatingUI /> },
  bid: { node: <BidManagementUI /> },
  takeoff: { node: <TakeoffUI /> },
  crm: { node: <CrmPipelineUI /> },
  crmHero: { node: <CrmHeroUI />, dark: true },
  crmWorkflow: { node: <CrmWorkflowUI /> },
  crmWorkspace: { node: <CrmWorkspaceUI /> },
  crmCustomer: { node: <CrmCustomerUI /> },
  crmOpportunity: { node: <CrmOpportunityUI />, dark: true },
  leadsHero: { node: <LeadsHeroUI />, dark: true },
  leadsWorkflow: { node: <LeadsWorkflowUI /> },
  leadsWorkspace: { node: <LeadsWorkspaceUI /> },
  leadsDetail: { node: <LeadsDetailUI /> },
  leadsDarkStory: { node: <LeadsDarkStoryUI />, dark: true },
  leadsActivity: { node: <LeadsActivityUI />, dark: true },
  leadsQualify: { node: <LeadsQualifyUI /> },
  leadsFollowUp: { node: <LeadsFollowUpUI /> },
  leadsNotes: { node: <LeadsNotesUI /> },
  leadsPriority: { node: <LeadsPriorityUI /> },
  leadsHandoff: { node: <LeadsHandoffUI /> },
  leadsPipelineDash: { node: <LeadsPipelineDashUI /> },
  leadsSources: { node: <LeadsSourcesUI /> },
  wbHero: { node: <WbHeroUI />, dark: true },
  wbTemplatePreview: { node: <WbTemplatePreviewUI /> },
  wbEditor: { node: <WbEditorUI /> },
  wbSectionEditor: { node: <WbSectionEditorUI /> },
  wbCmsImport: { node: <WbCmsImportUI />, dark: true },
  wbPortfolio: { node: <WbPortfolioUI /> },
  wbBranding: { node: <WbBrandingUI /> },
  wbSeo: { node: <WbSeoUI /> },
  wbPublish: { node: <WbPublishUI />, dark: true },
  wbDomain: { node: <WbDomainUI /> },
  wbDns: { node: <WbDnsUI /> },
  wbSsl: { node: <WbSslUI />, dark: true },
  wbContactLead: { node: <WbContactLeadUI />, dark: true },
  cpHero: { node: <CpHeroUI /> },
  cpShowcase: { node: <CpShowcaseUI /> },
  cpPortalScreen: { node: <CpPortalScreenUI /> },
  cpOwnerPortal: { node: <CpOwnerPortalUI /> },
  cpSubPortal: { node: <CpSubPortalUI /> },
  cpVendorPortal: { node: <CpVendorPortalUI /> },
  cpArchitectPortal: { node: <CpArchitectPortalUI /> },
  cpEsign: { node: <CpEsignUI /> },
  cpPermissions: { node: <CpPermissionsUI /> },
  cpActivity: { node: <CpActivityUI /> },
  cpApprovals: { node: <CpApprovalsUI /> },
  cpDocuments: { node: <CpDocumentsUI /> },
  cpFullPortal: { node: <CpFullPortalUI /> },
  precon: { node: <PreconWorkspaceUI /> },
  safety: { node: <SafetyUI /> },
  safetyOverview: { node: <SafetyOverviewUI /> },
  safetyObservation: { node: <SafetyObservationUI /> },
  safetyInspection: { node: <SafetyInspectionUI /> },
  safetyIncident: { node: <SafetyIncidentUI />, dark: true },
  safetyActions: { node: <SafetyActionsUI /> },
  safetyFlow: { node: <SafetyFlowUI /> },
  mobileHome: { node: <MobileHomeUI /> },
  mobileDashboard: { node: <MobileDashboardUI /> },
  mobileDailyLog: { node: <MobileDailyLogUI /> },
  mobileDrawing: { node: <MobileDrawingUI /> },
  mobilePhotos: { node: <MobilePhotosUI /> },
  mobilePunch: { node: <MobilePunchUI /> },
  mobileTm: { node: <MobileTmUI /> },
  mobileSafety: { node: <MobileSafetyUI /> },
  mobileWorkspace: { node: <MobileWorkspaceUI /> },
  mobileFlow: { node: <MobileFlowUI /> },
  mobileCapture: { node: <MobileCaptureUI /> },
  mobileChain: { node: <MobileChainUI /> },
  subDirectory: { node: <SubDirectoryUI /> },
  subProfile: { node: <SubProfileUI /> },
  subReadiness: { node: <SubReadinessUI /> },
  subInsurance: { node: <SubInsuranceUI />, dark: true },
  subLien: { node: <SubLienUI /> },
  subAlerts: { node: <SubAlertsUI /> },
  subApprovalFlow: { node: <SubApprovalFlowUI />, dark: true },
  compOverview: { node: <CompOverviewUI /> },
  compHealth: { node: <CompHealthUI /> },
  compRequirements: { node: <CompRequirementsUI /> },
  compSubReadiness: { node: <CompSubReadinessUI /> },
  compInsurance: { node: <CompInsuranceUI />, dark: true },
  compLien: { node: <CompLienUI /> },
  compAlerts: { node: <CompAlertsUI /> },
  compDocs: { node: <CompDocsUI /> },
  compApprovalFlow: { node: <CompApprovalFlowUI />, dark: true },
  wfOverview: { node: <WfOverviewUI /> },
  wfDirectory: { node: <WfDirectoryUI /> },
  wfProfile: { node: <WfProfileUI /> },
  wfCrew: { node: <WfCrewUI />, dark: true },
  wfProjectAssign: { node: <WfProjectAssignUI /> },
  wfLaborHours: { node: <WfLaborHoursUI /> },
  wfTimesheet: { node: <WfTimesheetUI /> },
  wfTimesheetApproval: { node: <WfTimesheetApprovalUI />, dark: true },
  wfCertifications: { node: <WfCertificationsUI /> },
  wfPayrollSummary: { node: <WfPayrollSummaryUI />, dark: true },
  wfCostFlow: { node: <WfCostFlowUI /> },
  timeOverview: { node: <TimeOverviewUI /> },
  timeWeekly: { node: <TimeWeeklyUI /> },
  timeEntry: { node: <TimeEntryUI /> },
  timeLaborBreakdown: { node: <TimeLaborBreakdownUI />, dark: true },
  timeProjectLabor: { node: <TimeProjectLaborUI /> },
  timeCostCode: { node: <TimeCostCodeUI /> },
  timeWorkflow: { node: <TimeWorkflowUI />, dark: true },
  timeApprovalQueue: { node: <TimeApprovalQueueUI /> },
  timeCostConnection: { node: <TimeCostConnectionUI />, dark: true },
  timePayrollSummary: { node: <TimePayrollSummaryUI /> },
  timeMobileEntry: { node: <TimeMobileEntryUI /> },
  timeSummary: { node: <TimeSummaryUI /> },
  prOverview: { node: <PrOverviewUI /> },
  prWorkflow: { node: <PrWorkflowUI /> },
  prPeriod: { node: <PrPeriodUI /> },
  prWorkerPay: { node: <PrWorkerPayUI /> },
  prLaborBreakdown: { node: <PrLaborBreakdownUI />, dark: true },
  prClassification: { node: <PrClassificationUI /> },
  prFringe: { node: <PrFringeUI /> },
  prSummary: { node: <PrSummaryUI /> },
  prReview: { node: <PrReviewUI />, dark: true },
  prProjectLabor: { node: <PrProjectLaborUI /> },
  prDataQuality: { node: <PrDataQualityUI /> },
  aiHero: { node: <AiHeroUI />, dark: true },
  aiWorkspace: { node: <AiWorkspaceUI />, dark: true },
  aiHowItWorks: { node: <AiHowItWorksUI /> },
  aiGrounded: { node: <AiGroundedUI />, dark: true },
  aiConfirm: { node: <AiConfirmUI /> },
  aiGroundedSources: { node: <AiGroundedSourcesUI />, dark: true },
  aiMultiModule: { node: <AiMultiModuleUI /> },
  aiDrawing: { node: <AiDrawingUI /> },
  aiFinancial: { node: <AiFinancialUI /> },
  aiField: { node: <AiFieldUI />, dark: true },
  aiDraftConfirm: { node: <AiDraftConfirmUI />, dark: true },
  aiHistory: { node: <AiHistoryUI /> },
  piHero: { node: <PiHeroUI />, dark: true },
  piWorkspace: { node: <PiWorkspaceUI />, dark: true },
  piHowItWorks: { node: <PiHowItWorksUI /> },
  piConnected: { node: <PiConnectedUI /> },
  piGrounded: { node: <PiGroundedUI />, dark: true },
  piStatus: { node: <PiStatusUI /> },
  piConfirm: { node: <PiConfirmUI /> },
  predHero: { node: <PredHeroUI />, dark: true },
  predShowcase: { node: <PredShowcaseUI />, dark: true },
  predRisk: { node: <PredRiskUI />, dark: true },
  predDetail: { node: <PredDetailUI /> },
  predPriority: { node: <PredPriorityUI />, dark: true },
  predHealth: { node: <PredHealthUI />, dark: true },
  predControl: { node: <PredControlUI /> },
  predForecast: { node: <PredForecastUI />, dark: true },
  predEarlyWarning: { node: <PredEarlyWarningUI />, dark: true },
  predSignalAction: { node: <PredSignalActionUI /> },
  predTrend: { node: <PredTrendUI />, dark: true },
  autoHero: { node: <AutoHeroUI />, dark: true },
  autoHowItWorks: { node: <AutoHowItWorksUI /> },
  autoShowcase: { node: <AutoShowcaseUI />, dark: true },
  autoApproval: { node: <AutoApprovalUI /> },
  autoActivityLog: { node: <AutoActivityLogUI /> },
  autoGovernance: { node: <AutoGovernanceUI />, dark: true },
  diHero: { node: <DiHeroUI />, dark: true },
  diQa: { node: <DiQaUI />, dark: true },
  diSummary: { node: <DiSummaryUI /> },
  diExtract: { node: <DiExtractUI /> },
  diCompare: { node: <DiCompareUI />, dark: true },
  diSearch: { node: <DiSearchUI /> },
  diContext: { node: <DiContextUI /> },
  diHowItWorks: { node: <DiHowItWorksUI /> },
  docs: { node: <DocsUI /> },
  documentCenter: { node: <DocumentCenterUI /> },
  documentDetail: { node: <DocumentDetailUI /> },
  documentUpload: { node: <DocumentUploadUI /> },
  drawingsWorkflow: { node: <DrawingsWorkflowUI /> },
  drawingWorkspace: { node: <DrawingWorkspaceUI /> },
  drawingRevision: { node: <DrawingRevisionUI />, dark: true },
  documentSearch: { node: <DocumentSearchUI /> },
  documentVersions: { node: <DocumentVersionsUI />, dark: true },
  documentConsolidate: { node: <DocumentConsolidateUI /> },
  drawingViewer: { node: <DrawingViewerDetailUI /> },
  drawingRegister: { node: <DrawingRegisterUI />, dark: true },
  drawingMarkup: { node: <DrawingMarkupUI /> },
  sheetsAsBuilt: { node: <SheetsAsBuiltUI /> },
  transmittal: { node: <TransmittalUI />, dark: true },
  fieldDrawing: { node: <FieldDrawingUI /> },
  dailyLogDashboard: { node: <DailyLogDashboardUI /> },
  dailyLogCapture: { node: <DailyLogCaptureUI /> },
  dailyLogDetail: { node: <DailyLogDetailUI />, dark: true },
  dailyLogHistory: { node: <DailyLogHistoryUI />, dark: true },
  dailyLogWorkforce: { node: <DailyLogWorkforceUI /> },
  dailyLogPhotos: { node: <DailyLogPhotosUI /> },
  punchDashboard: { node: <PunchDashboardUI /> },
  punchStatus: { node: <PunchStatusUI />, dark: true },
  punchAssign: { node: <PunchAssignUI /> },
  punchCloseout: { node: <PunchCloseoutUI />, dark: true },
  tmTicket: { node: <TmTicketUI /> },
  tmTicketDetail: { node: <TmTicketDetailUI />, dark: true },
  tmLabor: { node: <TmLaborUI /> },
  tmMaterials: { node: <TmMaterialsUI /> },
  tmEquipment: { node: <TmEquipmentUI /> },
  tmFlow: { node: <TmFlowUI /> },
  tmChange: { node: <TmChangeUI />, dark: true },
  tmAttachments: { node: <TmAttachmentsUI /> },
  tmReview: { node: <TmReviewUI /> },
  tmDashboard: { node: <TmDashboardUI />, dark: true },
  schedule: { node: <ScheduleUI /> },
  scheduleGantt: { node: <ScheduleGanttUI /> },
  scheduleDeps: { node: <ScheduleDependenciesUI /> },
  scheduleLookahead: { node: <ScheduleLookAheadUI /> },
  scheduleRisk: { node: <ScheduleRiskUI />, dark: true },
  scheduleExport: { node: <ScheduleExportUI /> },
  accounting: { node: <AccountingUI />, dark: true },
  accountingDashboard: { node: <AccountingDashboardUI />, dark: true },
  accountingAp: { node: <AccountingApUI />, dark: true },
  accountingAr: { node: <AccountingArUI />, dark: true },
  accountingProject: { node: <AccountingProjectUI />, dark: true },
  accountingReport: { node: <AccountingReportUI />, dark: true },
  accountingFlow: { node: <AccountingFlowUI /> },
  billingWorkspace: { node: <BillingWorkspaceUI />, dark: true },
  billingSov: { node: <BillingSovUI />, dark: true },
  billingProgress: { node: <BillingProgressUI />, dark: true },
  billingPayApp: { node: <BillingPayAppUI />, dark: true },
  billingAr: { node: <BillingArUI />, dark: true },
  billingFlow: { node: <BillingFlowUI /> },
  payAppDashboard: { node: <PayAppDashboardUI />, dark: true },
  payAppG702: { node: <PayAppG702UI />, dark: true },
  payAppG703: { node: <PayAppG703UI />, dark: true },
  payAppRetainage: { node: <PayAppRetainageUI />, dark: true },
  payAppHistory: { node: <PayAppHistoryUI />, dark: true },
  payAppReview: { node: <PayAppReviewUI />, dark: true },
  payAppFlow: { node: <PayAppFlowUI /> },
  wipDashboard: { node: <WipDashboardUI />, dark: true },
  wipProject: { node: <WipProjectUI />, dark: true },
  wipTable: { node: <WipTableUI />, dark: true },
  wipPortfolio: { node: <WipPortfolioUI />, dark: true },
  wipSnapshot: { node: <WipSnapshotUI />, dark: true },
  wipFlow: { node: <WipFlowUI /> },
  cashDashboard: { node: <CashDashboardUI />, dark: true },
  cashChart: { node: <CashChartUI />, dark: true },
  cashInflows: { node: <CashInflowsUI />, dark: true },
  cashOutflows: { node: <CashOutflowsUI />, dark: true },
  cashArAp: { node: <CashArApUI />, dark: true },
  cashProject: { node: <CashProjectUI />, dark: true },
  cashFlow: { node: <CashFlowUI /> },
  procurement: { node: <ProcurementUI /> },
  collaboration: { node: <CollaborationUI /> },
  reports: { node: <PortfolioAnalytics /> },
  rfi: { node: <RfiUI /> },
  rfiRegister: { node: <RfiRegisterUI /> },
  rfiCreate: { node: <RfiCreateUI /> },
  rfiDetail: { node: <RfiDetailUI />, dark: true },
  rfiResponse: { node: <RfiResponseUI /> },
  rfiFlow: { node: <RfiFlowUI /> },
  rfiStatus: { node: <RfiStatusUI /> },
  rfiContext: { node: <RfiContextUI /> },
  rfiField: { node: <RfiFieldUI /> },
  submittal: { node: <SubmittalUI /> },
  submittalRegister: { node: <SubmittalRegisterUI /> },
  submittalCreate: { node: <SubmittalCreateUI /> },
  submittalDetail: { node: <SubmittalDetailUI />, dark: true },
  submittalReview: { node: <SubmittalReviewUI /> },
  submittalFlow: { node: <SubmittalFlowUI /> },
  submittalStatus: { node: <SubmittalStatusUI /> },
  submittalWorkflow: { node: <SubmittalWorkflowUI /> },
  submittalDocs: { node: <SubmittalDocsUI /> },
  submittalField: { node: <SubmittalFieldUI /> },
  changeOrder: { node: <ChangeOrderUI />, dark: true },
  changeOrderRegister: { node: <ChangeOrderRegisterUI />, dark: true },
  changeOrderCreate: { node: <ChangeOrderCreateUI />, dark: true },
  changeOrderDetail: { node: <ChangeOrderDetailUI />, dark: true },
  changeOrderFlow: { node: <ChangeOrderFlowUI /> },
  changeOrderStatus: { node: <ChangeOrderStatusUI />, dark: true },
  changeOrderContext: { node: <ChangeOrderContextUI />, dark: true },
  projectCreate: { node: <ProjectCreateUI /> },
  projectDashboard: { node: <ProjectDashboardUI /> },
  projectFinancial: { node: <ProjectFinancialSummaryUI /> },
  projectPhases: { node: <ProjectPhasesTeamUI /> },
  projectSwitcher: { node: <ProjectSwitcherUI /> },
};

type Props = {
  preview: PreviewKey;
  dark?: boolean;
  className?: string;
  scale?: "sm" | "md" | "lg";
  /** Premium browser/app chrome around the product mockup */
  framed?: boolean;
};

export function FeatureProductPreview({
  preview,
  dark,
  className = "",
  scale = "lg",
  framed = false,
}: Props) {
  const entry = PREVIEWS[preview] ?? PREVIEWS.project;
  const isDark = dark ?? entry.dark;
  const scaleClass =
    scale === "lg"
      ? "origin-top-left scale-[0.52] sm:scale-[0.58] lg:scale-[0.68]"
      : scale === "sm"
        ? "origin-top-left scale-[0.30] sm:scale-[0.34]"
        : "origin-top-left scale-[0.45] sm:scale-[0.52] lg:scale-[0.58]";

  const body = (
    <div className={`pointer-events-none ${scaleClass} ${isDark ? "bg-brand-navy p-1.5" : "p-1.5"}`}>
      {entry.node}
    </div>
  );

  if (framed) {
    return (
      <div
        className={`relative overflow-hidden rounded-xl border border-brand-line/80 bg-white shadow-[0_20px_50px_-28px_rgba(8,35,63,0.35)] ${className}`}
        aria-hidden="true"
      >
        <div
          className={
            "flex items-center gap-2 border-b px-3.5 py-2.5 " +
            (isDark ? "border-white/10 bg-[#061525]" : "border-brand-line/70 bg-[#F7F9FC]")
          }
        >
          <span className="flex gap-1.5" aria-hidden="true">
            <span className="h-2.5 w-2.5 rounded-full bg-[#FF5F57]/90" />
            <span className="h-2.5 w-2.5 rounded-full bg-[#FEBC2E]/90" />
            <span className="h-2.5 w-2.5 rounded-full bg-[#28C840]/90" />
          </span>
          <div
            className={
              "ml-2 flex-1 truncate rounded-md border px-3 py-1 text-[10px] font-medium " +
              (isDark
                ? "border-white/10 bg-white/5 text-slate-400"
                : "border-brand-line bg-white text-brand-muted")
            }
          >
            app.vertexcms.com
          </div>
        </div>
        <div className={`relative overflow-hidden ${isDark ? "bg-brand-navy" : "bg-[#FAFBFD]"}`}>
          {body}
          <div
            className={
              "pointer-events-none absolute inset-x-0 bottom-0 h-16 bg-gradient-to-t to-transparent " +
              (isDark ? "from-[#061525]" : "from-[#FAFBFD]")
            }
          />
        </div>
      </div>
    );
  }

  return (
    <div
      className={`relative overflow-hidden rounded-xl border border-brand-line bg-[#FAFBFD] ${className}`}
      aria-hidden="true"
    >
      {body}
      <div className="pointer-events-none absolute inset-x-0 bottom-0 h-14 bg-gradient-to-t from-[#FAFBFD] to-transparent" />
    </div>
  );
}
