/**
 * Demo team profiles for UI / design review only.
 * Not real Vertex CMS employees. Replace via `approvedTeamMembers` or CMS
 * by setting `teamConfig.useDemoMembers = false`.
 */

import type { TeamMember } from "./content";

const portrait = (file: string) => `/marketing/team/demo/${file}`;

export const demoTeamMembers: TeamMember[] = [
  {
    id: "demo-mara-ellison",
    name: "Mara Ellison",
    role: "CEO / Co-Founder",
    department: "Leadership",
    bio: "Guides the product around one idea: construction teams should work from a single connected operating platform — not a stack of disconnected tools.",
    image: portrait("team-demo-mara-ellison.png"),
    linkedin: null,
    category: "leadership",
    featured: true,
    demoContent: true,
  },
  {
    id: "demo-julian-voss",
    name: "Julian Voss",
    role: "Chief Product Officer",
    department: "Product",
    bio: "Shapes how project, financial, and field workflows meet in the product — so the interface reflects how construction work actually moves.",
    image: portrait("team-demo-julian-voss.png"),
    linkedin: null,
    category: "leadership",
    demoContent: true,
  },
  {
    id: "demo-priya-raman",
    name: "Priya Raman",
    role: "Chief Technology Officer",
    department: "Engineering",
    bio: "Leads platform architecture, tenant isolation, and the systems that keep office, field, and financial data on the same record.",
    image: portrait("team-demo-priya-raman.png"),
    linkedin: null,
    category: "leadership",
    demoContent: true,
  },
  {
    id: "demo-elena-cho",
    name: "Elena Cho",
    role: "Senior Product Designer",
    department: "Product",
    bio: "Designs the product surfaces operators use every day — from project workspaces to field-ready flows — with a bias for clarity over decoration.",
    image: portrait("team-demo-elena-cho.png"),
    linkedin: null,
    category: "member",
    demoContent: true,
  },
  {
    id: "demo-nathan-brooks",
    name: "Nathan Brooks",
    role: "Product Manager",
    department: "Product",
    bio: "Connects customer workflows to the roadmap, keeping delivery scoped to what actually unblocks project and financial teams.",
    image: portrait("team-demo-nathan-brooks.png"),
    linkedin: null,
    category: "member",
    demoContent: true,
  },
  {
    id: "demo-imani-cole",
    name: "Imani Cole",
    role: "Frontend Engineer",
    department: "Engineering",
    bio: "Builds the application interface for office and field use, with attention to performance, accessibility, and consistent product patterns.",
    image: portrait("team-demo-imani-cole.png"),
    linkedin: null,
    category: "member",
    demoContent: true,
  },
  {
    id: "demo-rafael-duarte",
    name: "Rafael Duarte",
    role: "Backend Engineer",
    department: "Engineering",
    bio: "Works on the services that hold project, cost, and operational data together under tenant-scoped isolation.",
    image: portrait("team-demo-rafael-duarte.png"),
    linkedin: null,
    category: "member",
    demoContent: true,
  },
  {
    id: "demo-sofia-lindqvist",
    name: "Sofia Lindqvist",
    role: "Mobile Engineer",
    department: "Engineering",
    bio: "Builds the mobile workflows field teams use to capture work against the live project record.",
    image: portrait("team-demo-sofia-lindqvist.png"),
    linkedin: null,
    category: "member",
    demoContent: true,
  },
  {
    id: "demo-kenji-okada",
    name: "Kenji Okada",
    role: "AI / Intelligence Engineer",
    department: "Engineering",
    bio: "Develops governed intelligence features on connected project data — with confirmation before writes and a record of the action.",
    image: portrait("team-demo-kenji-okada.png"),
    linkedin: null,
    category: "member",
    demoContent: true,
  },
  {
    id: "demo-amara-bennett",
    name: "Amara Bennett",
    role: "Customer Success Manager",
    department: "Customer Experience",
    bio: "Helps teams adopt the platform across office and field, staying close to the operational problems the product is meant to solve.",
    image: portrait("team-demo-amara-bennett.png"),
    linkedin: null,
    category: "member",
    demoContent: true,
  },
  {
    id: "demo-owen-hart",
    name: "Owen Hart",
    role: "Implementation Specialist",
    department: "Operations",
    bio: "Guides new workspaces from first project setup through connected financial and field workflows.",
    image: portrait("team-demo-owen-hart.png"),
    linkedin: null,
    category: "member",
    demoContent: true,
  },
];
